name: sample-workflow
on: [push]
jobs:
  explore-first-github-workflow:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job ${{ job.name }} was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "The job is now running on ${{ runner.os }} server hosted by Github"
      - run: echo "The name of the branch is ${{ github.ref }} and the repository is ${{ github.repository }}."
      - name: Checkout repository code
        uses: actions/checkout@v2
      - run: echo "The Github repo ${{ github.repository }} has been cloned to the runner."
      - run: echo "The workflow is now ready to test your code in the runner."
      - name: List files in the cloned repository
        run: | 
          ls -la ${{ github.workspace }}
      - run: echo "This job status is ${{ job.status }}."
      
